footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 6.0

#layer definitions
static_map: true
static:
    map_topic: /map
    subscribe_to_updates: true

min_obstacle_height: 0.5

observation_sources: laser_scan_sensor front_laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: back_laser, data_type: LaserScan, topic: /back_scan, marking: true, clearing: true}
front_laser_scan_sensor: {sensor_frame: front_laser, data_type: LaserScan, topic: /front_scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: base_laser, data_type: PointCloud, topic: /my_cloud, marking: true, clearing: true}







# obstacle_range: 2.5
# raytrace_range: 3.0
# footprint: [[.2,.4], [.2,-.4], [-.2,.4], [-.2,-.4]]
# #robot_radius: ir_of_robot
# inflation_radius: 0.55

# # observation_sources: laser_scan_sensor point_cloud_sensor

# # laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

# # point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}