Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64" # bento/ubuntu-16.04
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    vb.memory = "16384"
  end
  config.vm.provision :shell, path: "vagrantConfig.sh"
  config.vm.provision :shell, path: "rosConfig.sh"
  config.vm.provision :shell, path: "gazeboConfig.sh"
  config.vm.provision :shell, path: "catkinConfig.sh"
end
